apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: skupper-site
  title: Skupper Site
  description: An skupper site that can be linked to others
  tags:
    - skupper
spec:
  owner: service@example.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - project
        - sitename
      properties:
        project:
          title: Project
          type: string
          description: The target OpenShift project
          default: "skupper"
        sitename:
          title: Site Name
          type: string
          description: The name for the skupper site.
        linkedsite:
          title: Linked Site
          type: string
          description: Site name to link to
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - 'spec.type':
                  - skupper-site
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          project: ${{ parameters.project }}
          sitename: ${{ parameters.sitename }}
          linkedsite: ${{ parameters.linkedsite }}

    - id: pull-request
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
        branchName: ${{ parameters.sitename }}
        title: skupper for ${{ parameters.sitename }}
        description: skupper for ${{ parameters.sitename }}
        
