apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: skupper-site
  title: Skupper Site
  description: An skupper site that can be linked to others
  tags:
    - skupper
spec:
  owner: service@example.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - project
        - sitename
      properties:
        project:
          title: Project
          type: string
          description: The target OpenShift project
          default: "skupper"
        sitename:
          title: Site Name
          type: string
          description: The name for the skupper site.
        linkedsite:
          title: Linked Site
          type: string
          description: Site name to link to
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - 'spec.type':
                  - skupper-site
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          project: ${{ parameters.project }}
          sitename: ${{ parameters.sitename }}
          linkedsite: ${{ parameters.linkedsite }}
          destination: "https://${{ parameters.repo.host }}/development/${{parameters.sitename}}"
          owner: ${{ user.entity.metadata.name }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.sitename}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog/${{parameters.sitename}}-skupper-site.yaml"


    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.sitename }}-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.sitename }}.git
        path: 'argo/'


        
